- name: Find existing operationtheater omod
  find:
    paths: /opt/openmrs/modules
    patterns: operationtheater*.omod
  register: result

- name: Delete operationtheater omod
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ result.files }}"

- name: Get operationtheater omod from openmrs bintray and place it in /opt/openmrs/modules
  get_url:
    url: "{{ operationtheater_omod }}"
    dest: /opt/openmrs/modules/
    mode: 0644
    owner: bahmni
    group: bahmni
